iron_web_api:
    resource: "@IronWebAPIBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#REST 
rest : 
  type : rest 
  resource : "routing_rest.yml"
  prefix : /api

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc