<?php

namespace IronWeb\APIBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleAnswerRepository extends EntityRepository
{
}
